# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: esdc_esasky@sciops.esa.int
author_name: European Space Agency
has_binder: true
has_settings: false
kind: frontend
labextension_name: pyesasky
project_short_description: ESASky Python wrapper
python_name: pyesasky
repository: https://github.com/esdc-esac-esa-int/pyesasky
test: true

